<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        async function fn() {
            //1、返回的结果不是一个promise类型的对象（像什么字符串，数字，
            //undefined等），则返回的结果就是成功的promise对象
            // return 'cjx';//cjx是一个字符串，看上去是返回字符串，但是字符串不是promise类型对象，所以
            //实际上返回的不是字符串，而是promise对象
            //2、抛出错误,则返回的是失败的promise对象
            // throw new Error('出错');
            //3、返回的是promise对象，则如果是成功的promise对象，则返回的就是成功的promise对象
            //如果是失败的promise对象，则返回的就是失败的promise对象
            return new Promise((resolve, reject) => {
                // resolve('成功的数据');
                reject('失败的数据');  
            })
        }
        const  result = fn();
        result.then(value => {
            console.log(value);
        }, reason => {
            console.log(reason);
        })
        // console.log(result);
    </script>
</body>
</html>