<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        const p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('用户数据');
                //reject('出错了！')''
            }, 1000);
        })

        //调用then方法，then方法的返回结果是Promise对象对象状态由回调函数的执行结果决定
        //1、如果回调函数中返回的结果是非promise类型，则promise对象的状态为成功
        //2、如果回调函数中返回的结果是promise类型，则返回的promise对象的状态决定了then方法返回的
        //promise对象的状态，也就是说如果回调函数返回的promise对象的状态是成功。那么then方法返回的promise对象
        //的状态也是成功的，如果是失败的，那么then方法返回的promise对象也是失败的
        //3、如果回调函数里面是抛出错误，则then方法返回的promise对象状态是错误的
        const result = p.then(value => {
            //1、非promise类型的值
            // return 'ccc';
            //2、是promise对象
            // return new Promise((resolve, reject) => {
            //     resolve('ok');
            //     // reject('err');
            // })
            //3、抛出错误
            throw '出问题了';
        }, reason => {
            console.warn(reason);
        })
        console.log(result);
    </script>
</body>
</html>